### ISSUE TITLE
Issue with latest 1.21 spigot build.

### ISSUE THREAD

**Issue by alexcrea** [stefvanschie/IF#1163]
Using IF 0.10.14 and latest version of spigot at the time (4227-Spigot-146439e-ee3d725) for 1.21, my GUI do not work anymore.

The issue occur simply by clicking an item on a PatternPane. (but probably unrelated to PatternPane)

Please note that I had updated my plugin for 1.21, and it was working fine as I was only using the simple chest inventory. 
The issue is coming from one of the Spigot latest changes. Check that you are using one of the latest spigot version before trying to replicate it.

Relevant part of the stack trace:
```
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
	at com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:68) ~[?:?]
```

Here is the full stack trace:
```
[01:19:01] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CustomAnvil v1.5.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:71) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:14) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4227-Spigot-146439e-ee3d725]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
	at com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:68) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 20 more
```

**Comment by alexcrea** [comment]
Never mind. I was using the plugin in an unsupported way that caused that issue.
Checking my tool chain configuration and fixing it made it work.

**Comment by Ghost-chu** [comment]
> Never mind. I was using the library in an unsupported way that caused that issue. Checking my tool chain configuration and fixing it made it work.

How did you fix that? I also encountered same issue.

**Comment by alexcrea** [comment]
> > Never mind. I was using the library in an unsupported way that caused that issue. Checking my tool chain configuration and fixing it made it work.
> 
> How did you fix that? I also encountered same issue.

Oh sorry, did not notice your comment, sorry for responding late.
I was not shading the library and using it using the libraries tag (yeah, even if it says that it is unsupported. But it was working for my case, so I did not bother)
So I just shade IF framework in my plugin. 

If it did not, fix it. Are you are supporting only 1.21 (The api-version (plugin.yml) is 1.21): check that you are using one of the latest spigot 1.21 version as dependency.
