### ISSUE TITLE
1.21 InventoryView error spam

### ISSUE THREAD

**Issue by MrRockis** [stefvanschie/IF#1170]
In 1.21 InventoryView was changed from class to a interface. This is causing a massive error spam on servers.

Stacktrace:
`[17:04:011 ERROR]: Could not pass event EntityPickupItemEvent to QuickShop-Hikari v6.2.0.5
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at QuickShop-Hikari-6.2.0.5.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onEntityPickupItem(GuiListener.java:228) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1256.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-44-8d91b85]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-44-8d91b85]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:515) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.world.entity.player.Player.touch(Player.java:638) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:603) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3123) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.world.entity.player.Player.tick(Player.java:287) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:836) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.network.Connection.tick(Connection.java:635) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1601) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1308) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-44-8d91b85]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
        
Another spigot thread for the change: https://www.spigotmc.org/threads/inventoryview-changed-to-interface-backwards-compatibility.651754/

**Comment by BensaTV** [comment]
Have the same error

**Comment by stefvanschie** [comment]
Thank you for the report, this will be fixed in version 0.10.16.
