### ISSUE TITLE
Legacy Material Nag with 1.17

### ISSUE THREAD

**Issue by auriium** [stefvanschie/IF#120]
I'm attempting to use IF in one of my projects, and have shaded it into my project and relocated it into a lib directory. The following ensues on plugin startup - I make use of VariableBar nowhere in the code - 

`[15:41:59 ERROR]: Fatal error trying to convert OpenTutorial v1.0.0-SNAPSHOT:xyz/auriium/opentutorial/libs/if/pane/component/util/VariableBar.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for GREEN_STAINED_GLASS_PANE. Did you forget to define a modern (1.13+) api-version in your plugin.yml?
        at org.bukkit.craftbukkit.v1_17_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:327) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:721) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.util.Commodore.convert(Commodore.java:174) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:382) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:169) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:192) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at xyz.auriium.opentutorial.libs.if.gui.type.util.Gui.<clinit>(Gui.java:662) ~[?:?]
        at xyz.auriium.opentutorial.spigot.gui.SpigotUserInterfacer.buildListMenu(SpigotUserInterfacer.java:24) ~[?:?]
        at xyz.auriium.opentutorial.spigot.TutorialCommand.graphicalCreate(TutorialCommand.java:129) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BaseCommand.executeCommand(BaseCommand.java:577) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BaseCommand.execute(BaseCommand.java:513) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2185) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1996) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1977) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:41:59 ERROR]: Fatal error trying to convert OpenTutorial v1.0.0-SNAPSHOT:xyz/auriium/opentutorial/libs/if/pane/component/ToggleButton.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for GREEN_STAINED_GLASS_PANE. Did you forget to define a modern (1.13+) api-version in your plugin.yml?
        at org.bukkit.craftbukkit.v1_17_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:327) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:721) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.util.Commodore.convert(Commodore.java:174) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:382) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:169) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at xyz.auriium.opentutorial.libs.if.gui.type.util.Gui.<clinit>(Gui.java:664) ~[?:?]
        at xyz.auriium.opentutorial.spigot.gui.SpigotUserInterfacer.buildListMenu(SpigotUserInterfacer.java:24) ~[?:?]
        at xyz.auriium.opentutorial.spigot.TutorialCommand.graphicalCreate(TutorialCommand.java:129) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BaseCommand.executeCommand(BaseCommand.java:577) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BaseCommand.execute(BaseCommand.java:513) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
        at xyz.auriium.opentutorial.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2185) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1996) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1977) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
`

**Comment by stefvanschie** [comment]
You should define an api-version in your plugin.yml, so that Bukkit doesn't try to convert modern materials to legacy materials.

**Comment by stefvanschie** [comment]
Closing this because of lack of activity. If this is still unresolved, please re-open this issue.
