### ISSUE TITLE
Exception when initializing Font in Paper build 78+

### ISSUE THREAD

**Issue by Jyguy** [stefvanschie/IF#1494]
When initializing a `Label` component with a `Font`, an exception occurs. This only happens in Paper 1.21.1 builds 78 and above.
```
Caused by: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
	at Chronova-paper-1.0.0.jar/xyz.reknown.chronova.if.util.SkullUtil.setSkull(SkullUtil.java:65) ~[Chronova-paper-1.0.0.jar:?]
	at Chronova-paper-1.0.0.jar/xyz.reknown.chronova.if.util.SkullUtil.getSkull(SkullUtil.java:43) ~[Chronova-paper-1.0.0.jar:?]
	at Chronova-paper-1.0.0.jar/xyz.reknown.chronova.if.font.CSVFont.lambda$new$1(CSVFont.java:46) ~[Chronova-paper-1.0.0.jar:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
```

**Comment by maartenvr98** [comment]
I'm having the same problem in 1.21.6:

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile [in thread "Server thread"]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
```
