### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class [MAIN PACKAGE].inventoryframework.font.util.Font

### ISSUE THREAD

**Issue by manul694** [stefvanschie/IF#273]
Sometimes appearing this error:
[13:56:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 't' in plugin Towny v0.98.3.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1850]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class manulcraft.manulbuilds.inventoryframework.font.util.Font
	at manulcraft.manulbuilds.gui.builds.show(builds.java:73) ~[ManulBuilds-BETA-b142.jar:?]
	at manulcraft.manulbuilds.commands.townybuilds.onCommand(townybuilds.java:40) ~[ManulBuilds-BETA-b142.jar:?]
	at com.palmergames.bukkit.towny.object.AddonCommand.execute(AddonCommand.java:42) ~[towny-0.98.3.5.jar:?]
	at com.palmergames.bukkit.towny.object.AddonCommand.execute(AddonCommand.java:38) ~[towny-0.98.3.5.jar:?]
	at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:889) ~[towny-0.98.3.5.jar:?]
	at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:543) ~[towny-0.98.3.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more

This is being fixed when I restart server, but I don't know why I getting this error. This error appearing randomly.

**Comment by stefvanschie** [comment]
> This is being fixed when I restart server

Does this mean this error occurs after you reload the server?

**Comment by manul694** [comment]
I don't use /reload.

**Comment by manul694** [comment]
Last time when I seen this problem is 17 December 2022.

**Comment by stefvanschie** [comment]
If you check the JAR file, is the Font class present in the right location?
