### ISSUE TITLE
IndexOutOfBoundsException - OutlinePane

### ISSUE THREAD

**Issue by juanvlr** [stefvanschie/IF#310]
I got an IndexOutOfBoundsException when using insertItem in a OutlinePane

Code :
```java
ChestGui gui = new ChestGui(3, ComponentHolder.of(Component.text("Points")));
gui.setOnGlobalClick(event -> event.setCancelled(true));

OutlinePane background = new OutlinePane(0, 0, 9, 3);
background.addItem(new GuiItem(new ItemStack(Material.GRAY_STAINED_GLASS_PANE)));
background.setRepeat(true);

gui.addPane(background);

OutlinePane housesPane = new OutlinePane(1, 1, 7, 1);

ItemStack gryffindorItemStack = new ItemStack(Material.RED_WOOL);
gryffindorItemStack.editMeta(meta -> meta.displayName(Component.text("Maison Gryffondor", TextColor.color(0xef5250))));

housesPane.insertItem(new GuiItem(gryffindorItemStack), 0);

ItemStack hufflepuffItemStack = new ItemStack(Material.YELLOW_WOOL);
hufflepuffItemStack.editMeta(meta -> meta.displayName(Component.text("Maison Poufsouffle", TextColor.color(0xf7c92f))));

housesPane.insertItem(new GuiItem(hufflepuffItemStack), 2);

ItemStack slitherinItemStack = new ItemStack(Material.GREEN_WOOL);
slitherinItemStack.editMeta(meta -> meta.displayName(Component.text("Maison Serpentard", TextColor.color(0x267f2c))));

housesPane.insertItem(new GuiItem(slitherinItemStack), 4);

ItemStack ravenclawItemStack = new ItemStack(Material.BLUE_WOOL);
ravenclawItemStack.editMeta(meta -> meta.displayName(Component.text("Maison Serdaigle", TextColor.color(0x20478a))));

housesPane.insertItem(new GuiItem(ravenclawItemStack), 6);

gui.addPane(housesPane);
```

Exception :
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
[16:13:43 INFO]: 	at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756)
[16:13:43 INFO]: 	at java.base/java.util.ArrayList.add(ArrayList.java:481)
[16:13:43 INFO]: 	at Houses-1.0-SNAPSHOT.jar//com.github.stefvanschie.inventoryframework.pane.OutlinePane.insertItem(OutlinePane.java:341)
```

**Comment by stefvanschie** [comment]
This is correct. `OutlinePane#insertItem(GuiItem, int)` will insert the item in between other items. For example, if you already have two items added, you can insert the item in between the first and the second item. You cannot add items at arbitrary positions, which you're currently doing - for example, inserting an item at index 2 doesn't work if there's only 1 item. If you just want to add items to the pane, you should use `OutlinePane#addItem(GuiItem)`.
