### ISSUE TITLE
IllegalArgumentException: Coordinates must be in-bounds

### ISSUE THREAD

**Issue by LaserSlime** [stefvanschie/IF#322]
After updating from 0.10.7 to 0.10.8 my gui stopped working. I've checked my code multiple times and there is nothing that is directly placed out of bounds. Despite this, I get this error:
`[15:53:52 ERROR]: [Duels] Exception while handling click event in inventory '§9Duels', slot=13, item=SPLASH_POTION
java.lang.IllegalArgumentException: Coordinates must be in-bounds: x = 10, y = 0; should be below 9 and 8
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.InventoryComponent.setItem(InventoryComponent.java:418) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.pane.OutlinePane.display(OutlinePane.java:242) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.pane.component.ToggleButton.display(ToggleButton.java:296) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.pane.MasonryPane.display(MasonryPane.java:126) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.InventoryComponent.display(InventoryComponent.java:351) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.type.ChestGui.show(ChestGui.java:122) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.type.util.Gui.update(Gui.java:229) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.gui.KitGui.lambda$new$4(KitGui.java:98) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.GuiItem.callAction(GuiItem.java:166) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.pane.OutlinePane.click(OutlinePane.java:289) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:203) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.type.ChestGui.click(ChestGui.java:161) ~[duels-0.1.0.jar:?]
        at net.slimenetworkmc.duels.shaded.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:82) ~[duels-0.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-365]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3159) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

It's really hard to narrow down what's exactly causing this since KitGui.java:98 is just the Gui update() method being called. I dont think it would even help and the code is obviously quite long so I just hope the stacktrace is enough.

**Comment by DavidTheExplorer** [comment]
Long stacktrace requires a long code, please share everything related to the GUI creation.

**Comment by stefvanschie** [comment]
Could you share the code related to the `ToggleButton`s you have in your `ChestGui`?

**Comment by LaserSlime** [comment]
This is the section where they are added.
```
		kitSelections = new HashMap<>();
		for(Kit currentKit : gameManager.getKits().values()) {
			ToggleButton queueButton = new ToggleButton(1, 1);
			KitConfiguration config = currentKit.getConfig();
			Arena arena = gameManager.getArenas().get(config.getArena());

			ItemBuilder disabledItem = new ItemBuilder(config.getSymbol()).name("§r" + config.getFullName()).lore("§7" + config.getDescription())
					.lore("§aMap: §b" + arena.getFullName() + (arena.getBuilders() != null ? " §aby§b " + arena.getBuilders() : "")).lore("§aRounds: §b" + config.getDefaultRounds()).lore("")
					.flags(ItemFlag.values());
			queueButton.setDisabledItem(new GuiItem(disabledItem.clone().lore("§dClick to join the queue.").create(), event -> {
				Player p = (Player) event.getWhoClicked();
				if(queuePlayer(p, currentKit))
					p.sendMessage(DuelsPlugin.PREFIX + "§aSuccessfully queued for kit §b" + config.getFullName() + "§a.");
			}));

			ItemStack enabledItem = disabledItem.clone().lore("§dClick to leave the queue.").glint().create();
			queueButton.setEnabledItem(new GuiItem(enabledItem, event -> {
				Player p = (Player) event.getWhoClicked();
				if(unqueuePlayer(p, currentKit))
					p.sendMessage(DuelsPlugin.PREFIX + "§aSuccessfully left queue for kit §b" + config.getFullName() + "§a.");
			}));

			MasonryPane kitSelection = kitSelections.get(config.getCategory());
			if(kitSelection == null) {
				kitSelection = new MasonryPane(9, 2);
//				kitSelection.setVisible(false);
			}
			kitSelection.addPane(queueButton);
			kitSelections.put(config.getCategory(), kitSelection);
		}
```

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in version 0.10.12.

**Comment by LaserSlime** [comment]
I just tested on the latest snapshot. While the items do show up and there are no more console errors, only the first one will execute it's even when clicked, the other ones toggle visibly but the event is not fired.

**Comment by stefvanschie** [comment]
Thank you, this should be fixed in the latest 0.10.12 snapshot.

**Comment by LaserSlime** [comment]
Nope, still exact same issues as before.

**Comment by LaserSlime** [comment]
Ok this is interesting. I've now built the project myself and this doesnt happen if I use that version. Using the version from the online repository still results in the same issue. And yes I am using 0.10.12-SNAPSHOT.

**Comment by stefvanschie** [comment]
The uploaded snapshot appears to be correct. Have you tried forcing Maven to update the snapshot with the -U flag? Or if you're using 0.10.13-SNAPSHOT or 0.10.13, it should also be updated.

**Comment by LaserSlime** [comment]
I'm using 0.10.13 and it's fixed. You should look into #589 instead.
