### ISSUE TITLE
Not Shading Correctly

### ISSUE THREAD

**Issue by Auriium** [stefvanschie/IF#77]
I first attempted to shade IF into my plugin. It did not work and never ended up in the plugin. So then i copied exact word-for-word, char-for-char your example, replacing my maven-shade-plugin configuration with yours. Still does not work. Please help!

Also, in-game stacktrace for not finding the lib
`Caused by: java.lang.NoClassDefFoundError: com/elytraforce/libs/inventoryframework/pane/Pane
at com.elytraforce.voidcore.commands.TeleportCommands$VisitCommand.onCommand(TeleportCommands.java:59) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-385]
... 17 more
Caused by: java.lang.ClassNotFoundException: com.elytraforce.libs.inventoryframework.pane.Pane
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[server.jar:git-Paper-385]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Paper-385]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at com.elytraforce.voidcore.commands.TeleportCommands$VisitCommand.onCommand(TeleportCommands.java:59) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-385]
... 17 more`

As well as the compiler log

`[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ voidcore ---
[INFO] Including com.intellectualsites.fawe:FAWE-Bukkit:jar:1.16-434 in the shaded jar.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\Matt\VoidCore\target\VoidCore-1.0.0-SNAPSHOT.jar with C:\Users\Matt\VoidCore\target\voidcore-1.0.0-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: C:\Users\Matt\VoidCore\target\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.328 s
[INFO] Finished at: 2020-11-08T20:34:22-07:00
[INFO] ------------------------------------------------------------------------
`

**Comment by stefvanschie** [comment]
Could you show your pom.xml?

**Comment by stefvanschie** [comment]
Closing this since it has been thirty days, if your issue isn't resolved, please reopen this issue.
